/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-vercel-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-vercel-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-vercel-postgres/drizzle";
export const enum_events_status = pgEnum("enum_events_status", [
  "draft",
  "published",
]);
export const enum__events_v_version_status = pgEnum(
  "enum__events_v_version_status",
  ["draft", "published"],
);
export const enum_articles_category = pgEnum("enum_articles_category", [
  "review",
  "editorial",
]);
export const enum_articles_rating = pgEnum("enum_articles_rating", [
  "0",
  "0.5",
  "1",
  "1.5",
  "2",
  "2.5",
  "3",
  "3.5",
  "4",
  "4.5",
  "5",
]);
export const enum_articles_status = pgEnum("enum_articles_status", [
  "draft",
  "published",
]);
export const enum__articles_v_version_category = pgEnum(
  "enum__articles_v_version_category",
  ["review", "editorial"],
);
export const enum__articles_v_version_rating = pgEnum(
  "enum__articles_v_version_rating",
  ["0", "0.5", "1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5"],
);
export const enum__articles_v_version_status = pgEnum(
  "enum__articles_v_version_status",
  ["draft", "published"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const locations = pgTable(
  "locations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    address: varchar("address").notNull(),
    city: varchar("city").notNull(),
    state: varchar("state").notNull(),
    zip: numeric("zip", { mode: "number" }).notNull(),
    url: varchar("url").notNull(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("locations_logo_idx").on(columns.logo),
    index("locations_updated_at_idx").on(columns.updatedAt),
    index("locations_created_at_idx").on(columns.createdAt),
  ],
);

export const events = pgTable(
  "events",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    description: jsonb("description"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    price: numeric("price", { mode: "number" }),
    location: integer("location_id").references(() => locations.id, {
      onDelete: "set null",
    }),
    datetime: timestamp("datetime", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    paymentLink: varchar("payment_link"),
    productId: varchar("product_id"),
    priceId: varchar("price_id"),
    ticketLimit: numeric("ticket_limit", { mode: "number" }),
    ticketsSold: numeric("tickets_sold", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_events_status("_status").default("draft"),
  },
  (columns) => [
    index("events_image_idx").on(columns.image),
    index("events_location_idx").on(columns.location),
    uniqueIndex("events_payment_link_idx").on(columns.paymentLink),
    uniqueIndex("events_product_id_idx").on(columns.productId),
    uniqueIndex("events_price_id_idx").on(columns.priceId),
    index("events_updated_at_idx").on(columns.updatedAt),
    index("events_created_at_idx").on(columns.createdAt),
    index("events__status_idx").on(columns._status),
  ],
);

export const _events_v = pgTable(
  "_events_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => events.id, {
      onDelete: "set null",
    }),
    version_name: varchar("version_name"),
    version_description: jsonb("version_description"),
    version_image: integer("version_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_price: numeric("version_price", { mode: "number" }),
    version_location: integer("version_location_id").references(
      () => locations.id,
      {
        onDelete: "set null",
      },
    ),
    version_datetime: timestamp("version_datetime", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_paymentLink: varchar("version_payment_link"),
    version_productId: varchar("version_product_id"),
    version_priceId: varchar("version_price_id"),
    version_ticketLimit: numeric("version_ticket_limit", { mode: "number" }),
    version_ticketsSold: numeric("version_tickets_sold", {
      mode: "number",
    }).default(0),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__events_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_events_v_parent_idx").on(columns.parent),
    index("_events_v_version_version_image_idx").on(columns.version_image),
    index("_events_v_version_version_location_idx").on(
      columns.version_location,
    ),
    index("_events_v_version_version_payment_link_idx").on(
      columns.version_paymentLink,
    ),
    index("_events_v_version_version_product_id_idx").on(
      columns.version_productId,
    ),
    index("_events_v_version_version_price_id_idx").on(columns.version_priceId),
    index("_events_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_events_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_events_v_version_version__status_idx").on(columns.version__status),
    index("_events_v_created_at_idx").on(columns.createdAt),
    index("_events_v_updated_at_idx").on(columns.updatedAt),
    index("_events_v_latest_idx").on(columns.latest),
  ],
);

export const merch = pgTable(
  "merch",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    productId: varchar("product_id"),
    merchLimit: numeric("merch_limit", { mode: "number" }),
    merchSold: numeric("merch_sold", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("merch_product_id_idx").on(columns.productId),
    index("merch_updated_at_idx").on(columns.updatedAt),
    index("merch_created_at_idx").on(columns.createdAt),
  ],
);

export const orders = pgTable(
  "orders",
  {
    id: serial("id").primaryKey(),
    checkoutSessionId: varchar("checkout_session_id").notNull(),
    productId: varchar("product_id").notNull(),
    customerId: varchar("customer_id").notNull(),
    price: numeric("price", { mode: "number" }).notNull(),
    amountPaid: numeric("amount_paid", { mode: "number" }).notNull(),
    quantity: numeric("quantity", { mode: "number" }).notNull(),
    transactionDate: timestamp("transaction_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    receiptUrl: varchar("receipt_url").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("orders_checkout_session_id_idx").on(columns.checkoutSessionId),
    uniqueIndex("orders_receipt_url_idx").on(columns.receiptUrl),
    index("orders_updated_at_idx").on(columns.updatedAt),
    index("orders_created_at_idx").on(columns.createdAt),
  ],
);

export const orders_rels = pgTable(
  "orders_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    eventsID: integer("events_id"),
    merchID: integer("merch_id"),
  },
  (columns) => [
    index("orders_rels_order_idx").on(columns.order),
    index("orders_rels_parent_idx").on(columns.parent),
    index("orders_rels_path_idx").on(columns.path),
    index("orders_rels_events_id_idx").on(columns.eventsID),
    index("orders_rels_merch_id_idx").on(columns.merchID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [orders.id],
      name: "orders_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["eventsID"]],
      foreignColumns: [events.id],
      name: "orders_rels_events_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["merchID"]],
      foreignColumns: [merch.id],
      name: "orders_rels_merch_fk",
    }).onDelete("cascade"),
  ],
);

export const authors = pgTable(
  "authors",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    bio: varchar("bio"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("authors_image_idx").on(columns.image),
    index("authors_updated_at_idx").on(columns.updatedAt),
    index("authors_created_at_idx").on(columns.createdAt),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    body: jsonb("body"),
    category: enum_articles_category("category"),
    rating: enum_articles_rating("rating"),
    movie: varchar("movie"),
    author: integer("author_id").references(() => authors.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_articles_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("articles_slug_idx").on(columns.slug),
    index("articles_image_idx").on(columns.image),
    index("articles_author_idx").on(columns.author),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
    index("articles__status_idx").on(columns._status),
  ],
);

export const _articles_v = pgTable(
  "_articles_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => articles.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_image: integer("version_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_body: jsonb("version_body"),
    version_category: enum__articles_v_version_category("version_category"),
    version_rating: enum__articles_v_version_rating("version_rating"),
    version_movie: varchar("version_movie"),
    version_author: integer("version_author_id").references(() => authors.id, {
      onDelete: "set null",
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__articles_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_articles_v_parent_idx").on(columns.parent),
    index("_articles_v_version_version_slug_idx").on(columns.version_slug),
    index("_articles_v_version_version_image_idx").on(columns.version_image),
    index("_articles_v_version_version_author_idx").on(columns.version_author),
    index("_articles_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_articles_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_articles_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_articles_v_created_at_idx").on(columns.createdAt),
    index("_articles_v_updated_at_idx").on(columns.updatedAt),
    index("_articles_v_latest_idx").on(columns.latest),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    locationsID: integer("locations_id"),
    eventsID: integer("events_id"),
    merchID: integer("merch_id"),
    ordersID: integer("orders_id"),
    authorsID: integer("authors_id"),
    articlesID: integer("articles_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_locations_id_idx").on(
      columns.locationsID,
    ),
    index("payload_locked_documents_rels_events_id_idx").on(columns.eventsID),
    index("payload_locked_documents_rels_merch_id_idx").on(columns.merchID),
    index("payload_locked_documents_rels_orders_id_idx").on(columns.ordersID),
    index("payload_locked_documents_rels_authors_id_idx").on(columns.authorsID),
    index("payload_locked_documents_rels_articles_id_idx").on(
      columns.articlesID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["locationsID"]],
      foreignColumns: [locations.id],
      name: "payload_locked_documents_rels_locations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["eventsID"]],
      foreignColumns: [events.id],
      name: "payload_locked_documents_rels_events_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["merchID"]],
      foreignColumns: [merch.id],
      name: "payload_locked_documents_rels_merch_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["ordersID"]],
      foreignColumns: [orders.id],
      name: "payload_locked_documents_rels_orders_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["authorsID"]],
      foreignColumns: [authors.id],
      name: "payload_locked_documents_rels_authors_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_locations = relations(locations, ({ one }) => ({
  logo: one(media, {
    fields: [locations.logo],
    references: [media.id],
    relationName: "logo",
  }),
}));
export const relations_events = relations(events, ({ one }) => ({
  image: one(media, {
    fields: [events.image],
    references: [media.id],
    relationName: "image",
  }),
  location: one(locations, {
    fields: [events.location],
    references: [locations.id],
    relationName: "location",
  }),
}));
export const relations__events_v = relations(_events_v, ({ one }) => ({
  parent: one(events, {
    fields: [_events_v.parent],
    references: [events.id],
    relationName: "parent",
  }),
  version_image: one(media, {
    fields: [_events_v.version_image],
    references: [media.id],
    relationName: "version_image",
  }),
  version_location: one(locations, {
    fields: [_events_v.version_location],
    references: [locations.id],
    relationName: "version_location",
  }),
}));
export const relations_merch = relations(merch, () => ({}));
export const relations_orders_rels = relations(orders_rels, ({ one }) => ({
  parent: one(orders, {
    fields: [orders_rels.parent],
    references: [orders.id],
    relationName: "_rels",
  }),
  eventsID: one(events, {
    fields: [orders_rels.eventsID],
    references: [events.id],
    relationName: "events",
  }),
  merchID: one(merch, {
    fields: [orders_rels.merchID],
    references: [merch.id],
    relationName: "merch",
  }),
}));
export const relations_orders = relations(orders, ({ many }) => ({
  _rels: many(orders_rels, {
    relationName: "_rels",
  }),
}));
export const relations_authors = relations(authors, ({ one }) => ({
  image: one(media, {
    fields: [authors.image],
    references: [media.id],
    relationName: "image",
  }),
}));
export const relations_articles = relations(articles, ({ one }) => ({
  image: one(media, {
    fields: [articles.image],
    references: [media.id],
    relationName: "image",
  }),
  author: one(authors, {
    fields: [articles.author],
    references: [authors.id],
    relationName: "author",
  }),
}));
export const relations__articles_v = relations(_articles_v, ({ one }) => ({
  parent: one(articles, {
    fields: [_articles_v.parent],
    references: [articles.id],
    relationName: "parent",
  }),
  version_image: one(media, {
    fields: [_articles_v.version_image],
    references: [media.id],
    relationName: "version_image",
  }),
  version_author: one(authors, {
    fields: [_articles_v.version_author],
    references: [authors.id],
    relationName: "version_author",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    locationsID: one(locations, {
      fields: [payload_locked_documents_rels.locationsID],
      references: [locations.id],
      relationName: "locations",
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: "events",
    }),
    merchID: one(merch, {
      fields: [payload_locked_documents_rels.merchID],
      references: [merch.id],
      relationName: "merch",
    }),
    ordersID: one(orders, {
      fields: [payload_locked_documents_rels.ordersID],
      references: [orders.id],
      relationName: "orders",
    }),
    authorsID: one(authors, {
      fields: [payload_locked_documents_rels.authorsID],
      references: [authors.id],
      relationName: "authors",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_events_status: typeof enum_events_status;
  enum__events_v_version_status: typeof enum__events_v_version_status;
  enum_articles_category: typeof enum_articles_category;
  enum_articles_rating: typeof enum_articles_rating;
  enum_articles_status: typeof enum_articles_status;
  enum__articles_v_version_category: typeof enum__articles_v_version_category;
  enum__articles_v_version_rating: typeof enum__articles_v_version_rating;
  enum__articles_v_version_status: typeof enum__articles_v_version_status;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  locations: typeof locations;
  events: typeof events;
  _events_v: typeof _events_v;
  merch: typeof merch;
  orders: typeof orders;
  orders_rels: typeof orders_rels;
  authors: typeof authors;
  articles: typeof articles;
  _articles_v: typeof _articles_v;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_locations: typeof relations_locations;
  relations_events: typeof relations_events;
  relations__events_v: typeof relations__events_v;
  relations_merch: typeof relations_merch;
  relations_orders_rels: typeof relations_orders_rels;
  relations_orders: typeof relations_orders;
  relations_authors: typeof relations_authors;
  relations_articles: typeof relations_articles;
  relations__articles_v: typeof relations__articles_v;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-vercel-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
