// GENERATED by scripts/gen-email-fixtures.tsx — do not edit by hand.
// Real OMDB / Open Library data captured for local email previews.
// Regenerate: npm run email:fixtures
import type { MovieData } from '@/lib/omdb';
import type { BookInfo } from '@/emails/BroadcastEmail';

export const zvcMovie: MovieData = {
  title: 'The Thing',
  year: '1982',
  rated: 'R',
  runtime: '109 min',
  genre: 'Horror, Mystery, Sci-Fi',
  director: 'John Carpenter',
  actors: 'Kurt Russell, Wilford Brimley, Keith David',
  plot: 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.',
  imdbRating: '8.2',
  poster:
    'https://m.media-amazon.com/images/M/MV5BYTA3NDU5MWEtNTk4Yy00ZDNkLThmZTQtMjU3ZGVhYzAyMzU4XkEyXkFqcGc@._V1_SX1000.jpg',
};

export const ahcMovie: MovieData = {
  title: 'Halloween',
  year: '1978',
  rated: 'R',
  runtime: '91 min',
  genre: 'Horror, Thriller',
  director: 'John Carpenter',
  actors: 'Donald Pleasence, Jamie Lee Curtis, Tony Moran',
  plot: 'Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois, to kill again.',
  imdbRating: '7.7',
  poster:
    'https://m.media-amazon.com/images/M/MV5BMzZiNTdiYTgtYjNkMS00MmJmLWEwZGQtNmY0NGJkMGE0YmYzXkEyXkFqcGc@._V1_SX1000.jpg',
};

export const bookInfo: BookInfo = {
  title: 'The Haunting of Hill House',
  author: 'Shirley Jackson',
  cover: 'https://covers.openlibrary.org/b/id/4289014-L.jpg',
  description:
    'First published in 1959, Shirley Jackson\'s The Haunting of Hill House has been hailed as a perfect work of unnerving terror. It is the story of four seekers who arrive at a notoriously unfriendly pile called Hill House: Dr. Montague, an occult scholar looking for solid evidence of a "haunting"; Theodora, his lighthearted assistant; Eleanor, a friendless, fragile young woman well acquainted with poltergeists; and Luke, the future heir of Hill House. At first, their stay seems destined to be merely a spooky encounter with inexplicable phenomena. But Hill House is gathering its powers— and soon, it will choose one of them to make its own.',
};
