/**
 * Capture real OMDB / Open Library data for the local email previews and write
 * it to emails/previews/fixtures.generated.ts (committed, so `npm run dev:email`
 * works offline with genuine plots, posters, ratings, and book covers).
 *
 *   npm run email:fixtures        # needs OMDB_API_KEY (loaded via --env-file)
 *
 * Change the titles below and re-run to refresh the preview content.
 */
import { writeFileSync } from 'fs';
import path from 'path';
import { fetchMovieDataByImdbId } from '../lib/omdb';
import {
  searchBookByTitleAuthor,
  fetchBookDataByOpenLibraryId,
} from '../lib/openlibrary';

// The films/book shown in the previews — real IMDb ids / title+author.
const ZVC_IMDB_ID = 'tt0084787'; // The Thing (1982) — paid ZVC screening
const AHC_IMDB_ID = 'tt0077651'; // Halloween (1978) — free Astoria Horror Club
const BOOK_TITLE = 'The Haunting of Hill House';
const BOOK_AUTHOR = 'Shirley Jackson';

async function main() {
  const [zvcMovie, ahcMovie] = await Promise.all([
    fetchMovieDataByImdbId(ZVC_IMDB_ID),
    fetchMovieDataByImdbId(AHC_IMDB_ID),
  ]);
  if (!zvcMovie || !ahcMovie) {
    throw new Error(
      'OMDB fetch failed — check OMDB_API_KEY (run with --env-file=.env.local)'
    );
  }

  const bookSearch = await searchBookByTitleAuthor(BOOK_TITLE, BOOK_AUTHOR);
  const bookData = bookSearch?.workId
    ? await fetchBookDataByOpenLibraryId(bookSearch.workId)
    : null;
  const bookInfo = {
    title: bookSearch?.title ?? BOOK_TITLE,
    author: bookSearch?.author ?? BOOK_AUTHOR,
    cover: bookData?.cover || bookSearch?.cover || '',
    description: bookData?.description ?? '',
  };

  const file = `// GENERATED by scripts/gen-email-fixtures.tsx — do not edit by hand.
// Real OMDB / Open Library data captured for local email previews.
// Regenerate: npm run email:fixtures
import type { MovieData } from '@/lib/omdb';
import type { BookInfo } from '@/emails/BroadcastEmail';

export const zvcMovie: MovieData = ${JSON.stringify(zvcMovie, null, 2)};

export const ahcMovie: MovieData = ${JSON.stringify(ahcMovie, null, 2)};

export const bookInfo: BookInfo = ${JSON.stringify(bookInfo, null, 2)};
`;

  const outPath = path.join(
    process.cwd(),
    'emails/previews/fixtures.generated.ts'
  );
  writeFileSync(outPath, file);

  console.log(`Wrote ${path.relative(process.cwd(), outPath)}`);
  console.log(`  ZVC : ${zvcMovie.title} (${zvcMovie.year})  ★${zvcMovie.imdbRating}`);
  console.log(`  AHC : ${ahcMovie.title} (${ahcMovie.year})  ★${ahcMovie.imdbRating}`);
  console.log(
    `  Book: ${bookInfo.title} — ${bookInfo.author}  ${bookInfo.cover ? '(cover ✓)' : '(no cover)'}`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
